export enum webToManMsg {
  SetLang = 'setLang',
  GetLang = 'getLang',
  //user
  Login = 'Login',
  getCurUserInfo = 'getCurUserInfo',
  isLogin = 'isLogin',
  Register = 'Register',
  Logout = 'Logout',
  getAllUser = 'getAllUser',
  GetLastUserInfo = 'getLastUser',
  UpdateUser = 'UpdateUser',

  //valut
  GetAllValuts = 'GetAllValuts',
  UpdateValut = 'UpdateValut',
  DeleteValut = 'DeleteValut',
  AddValut = 'AddValut',

  //vaultItem
  GetAllValutItems = 'GetAllValutItems',
  updateValutItem = 'updateValutItem',
  DeleteValutItem = 'DeleteValutItem',
  AddValutItem = 'AddValutItem',

  //other
  ResizeWindow = 'ResizeWindow',
  GetWinBasePath = 'GetWinBasePath',
  isLock = 'isLock',
  LockApp = 'LockApp',
  UnLockApp = 'UnLockApp',
  IsSystemInit = 'IsSystemInit',
  AutoFill = 'AutoFill',
  ShortCutKeyChange = 'ShortCutKeyChange',
  CheckShortKey = 'CheckShortKey',
  getMousePos = 'getMousePos',
  showWindows = 'showWindows',
  ShowVaultItem = 'ShowItem',
  UpdateTrayMenu = 'UpdateTrayMenu',
  Backup_local = 'BackupFromLocal',
  Recover_local = 'RestoreFromLocal',
  Backup_alidrive = 'BackupFromAliDrive',
  Recover_alidrive = 'RestoreFromAliDrive',
  Delete_alidrive_file = 'DeleteFromAliDrive',
  Trash_alidrive_file = 'trashFromAliDrive',
  GetAllBackups_alidrive = 'GetAllBackupsFromAliDrive',
  QuitAPP = 'QuitAPP',
  ImportCSV = 'ImportCSV',
  ExputCSV = 'ExputCSV',
  RestartApp = 'RestartApp',
  CloseDb = 'CloseDb',
  OpenDb = 'OpenDb',
  getLogLevel = 'getLogLevel',
  ChangeMainPassword = 'ChangeMainPassword',
  getAppVersion = 'getAppVersion',
  checkUpdate = 'checkUpdate',
  CancelUpdate = 'CancelUpdate',
  checkUpdateAuto = 'checkUpdateAuto',
  Downloadupdate = 'Downloadupdate',
  PowerOnOpen = 'PowerOnOpen',
  InstallUpdate = 'InstallUpdate',
  CheckUpdateStatus = 'CheckUpdateStatus',
  IsVaultChangeNotBackup = 'IsVaultChangeNotBackup',
  OpenShell = 'OpenShell'
}

export enum MainToWebMsg {
  ShowMsg = 'ShowMsg',
  ShowMsgMain = 'ShowMsgMain',
  LockApp = 'lockApp',
  LoginOK = 'LoginOk',
  LoginOut = 'LoginOut',
  UserChange = 'userchange',
  VaultChange = 'vaultchange',
  vaultItemChange = 'vaultItemChange',
  DataChange = 'DataChange',
  ShowVaulteItem = 'ShowVaulteItem',
  AliyunAuthOk = 'AliyunAuthOk',
  LangChange = 'LangChange',
  AppUpdateEvent = 'UpdateEvent',
  VaultChangeNotBackup = 'VaultChangeNotBackup',
  WindowsHide = 'windosHide'
}
